language: python
python: 2.7
sudo: false

install:
  - pip install --process-dependency-links -e .[dev]

addons:
  apt:
    sources:
      - mongodb-upstart
      - mongodb-3.0-precise
    packages:
      - mongodb-org-server
      - mongodb-org-shell

before_script:
  - "until nc -z localhost 27017; do echo Waiting for MongoDB; sleep 1; done"

script:
  - trial benchmark
